### ISSUE TITLE
Deployed to Solana mainnet?

### ISSUE THREAD

**Issue by tahpot** [identity-com/sol-did#95]
The documentation states the program is deployed to Solana mainnet `idDa4XeCjVwKcprVAo812coUQbovSZ4kDGJf2sPaBnM`, but there is nothing there: https://explorer.solana.com/address/idDa4XeCjVwKcprVAo812coUQbovSZ4kDGJf2sPaBnM

**Comment by solidnerd** [comment]
Hey @tahpot, 
You were right. It wasn't deployed when you were asking for it. It's finally deployed now for at least two months.

**Comment by tahpot** [comment]
Thanks @solidnerd
